spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/toonsearch
    driver-class-name: org.mariadb.jdbc.Driver
    username: toonsearch_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true